// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kbkgthyiepfuzulpkcwi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtia2d0aHlpZXBmdXp1bHBrY3dpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyMTYyODUsImV4cCI6MjA3Mzc5MjI4NX0.sORZOkkDrGeyg88dw2qIlsnD8hhFC27Q5K6-vRzaz8U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});